INSERT INTO product_sort (id, enum_class, type, sort, description, mean_grade) 
VALUES 
(1, 0, 'Apple', 'Braeburn', 'Apple Braeburn', 0),
(2, 0, 'Apple', 'Crimson Snow', 'Apple Crimson Snow', 0),
(3, 0, 'Apple', 'Golden', 'Apple Golden 2', 0),
(4, 0, 'Apple', 'Granny Smith', 'Apple Granny Smith', 0),
(5, 0, 'Apple', 'Pink Lady', 'Apple Pink Lady', 0),
(6, 0, 'Apple', 'Red', 'Apple Red 1', 0),
(7, 0, 'Apple', 'Red Delicious', 'Apple Red Delicious', 0),
(8, 0, 'Apple', 'Red Yellow', 'Apple Red Yellow 1', 0),
(9, 0, 'Apricot', 'Original', 'Apricot', 0),
(10, 0, 'Avocado', 'Original', 'Avocado', 0),
(11, 0, 'Avocado ripe', 'Ripe', 'Avocado ripe', 0),
(12, 0, 'Banana', 'Original', 'Banana', 0),
(13, 0, 'Banana', 'Lady Finger', 'Banana Lady Finger', 0),
(14, 0, 'Banana', 'Red', 'Banana Red', 0),
(15, 1, 'Beetroot', 'Original', 'Beetroot', 0),
(16, 0, 'Melon', 'Cantaloupe', 'Cantaloupe 1', 0),
(17, 1, 'Cauliflower', 'Original', 'Cauliflower', 0),
(18, 0, 'Cherry', 'Original', 'Cherry 1', 0),
(19, 0, 'Cherry', 'Rainier', 'Cherry Rainier', 0),
(20, 0, 'Cherry', 'Wax Black', 'Cherry Wax Black', 0),
(21, 0, 'Cherry', 'Wax Red', 'Cherry Wax Red', 0),
(22, 0, 'Cherry', 'Wax Yellow', 'Cherry Wax Yellow', 0),
(23, 0, 'Clementine', 'Original', 'Clementine', 0),
(24, 0, 'Cocos', 'Original', 'Cocos', 0),
(25, 1, 'Corn', 'Original', 'Corn', 0),
(26, 2, 'Blueberry', 'Original', 'Blueberry', 0),
(27, 1, 'Corn', 'Husk', 'Corn Husk', 0),
(28, 1, 'Cucumber', 'Ripe', 'Cucumber Ripe 2', 0),
(29, 0, 'Dates', 'Original', 'Dates', 0),
(30, 1, 'Eggplant', 'Original', 'Eggplant', 0),
(31, 1, 'Ginger Root', 'Original', 'Ginger Root', 0),
(32, 0, 'Grape', 'Blue', 'Grape Blue', 0),
(33, 0, 'Grape', 'Pink', 'Grape Pink', 0),
(34, 0, 'Grape', 'White', 'Grape White', 0),
(35, 0, 'Grapefruit', 'Pink', 'Grapefruit Pink', 0),
(36, 0, 'Grapefruit', 'White', 'Grapefruit White', 0),
(37, 2, 'Huckleberry', 'Original', 'Huckleberry', 0),
(38, 0, 'Kaki', 'Original', 'Kaki', 0),
(39, 0, 'Kiwi', 'Original', 'Kiwi', 0),
(40, 0, 'Lemon', 'Original', 'Lemon', 0),
(41, 0, 'Lemon', 'Meyer', 'Lemon Meyer', 0),
(42, 0, 'Lime', 'Original', 'Limes', 0),
(43, 0, 'Mandarine', 'Original', 'Mandarine', 0),
(44, 0, 'Mango', 'Original', 'Mango', 0),
(45, 0, 'Mango', 'Red', 'Mango Red', 0),
(46, 0, 'Melon', 'Piel de Sapo', 'Melon Piel de Sapo', 0),
(47, 0, 'Mulberry', 'Original', 'Mulberry', 0),
(48, 0, 'Nectarine', 'Original', 'Nectarine', 0),
(49, 1, 'Onion', 'Red', 'Onion Red', 0),
(50, 1, 'Onion', 'Red Peeled', 'Onion Red Peeled', 0),
(51, 1, 'Onion', 'White', 'Onion White', 0),
(52, 0, 'Orange', 'Original', 'Orange', 0),
(53, 0, 'Passion Fruit', 'Original', 'Passion Fruit', 0),
(54, 0, 'Peach', 'Original', 'Peach', 0),
(55, 0, 'Pear', 'Original', 'Pear 2', 0),
(56, 0, 'Pear', 'Abate', 'Pear Abate', 0),
(57, 0, 'Pear', 'Forelle', 'Pear Forelle', 0),
(58, 0, 'Pear', 'Kaiser', 'Pear Kaiser', 0),
(59, 0, 'Pear', 'Monster', 'Pear Monster', 0),
(60, 0, 'Pear', 'Red', 'Pear Red', 0),
(61, 0, 'Pear', 'Williams', 'Pear Williams', 0),
(62, 1, 'Pepper', 'Green', 'Pepper Green', 0),
(63, 1, 'Pepper', 'Orange', 'Pepper Orange', 0),
(64, 1, 'Pepper', 'Red', 'Pepper Red', 0),
(65, 1, 'Pepper', 'Yellow', 'Pepper Yellow', 0),
(66, 0, 'Pineapple', 'Origin', 'Pineapple', 0),
(67, 0, 'Pineapple', 'Mini', 'Pineapple Mini', 0),
(68, 0, 'Pitahaya', 'Red', 'Pitahaya Red', 0),
(69, 0, 'Plum', 'Original', 'Plum', 0),
(70, 0, 'Pomegranate', 'Original', 'Pomegranate', 0),
(71, 0, 'Pomelo', 'Sweetie', 'Pomelo Sweetie', 0),
(72, 1, 'Potato', 'Sweet', 'Potato Sweet', 0),
(73, 1, 'Potato', 'White', 'Potato White', 0),
(74, 0, 'Quince', 'Original', 'Quince', 0),
(75, 2, 'Raspberry', 'Original', 'Raspberry', 0),
(76, 2, 'Strawberry', 'Original', 'Strawberry', 0),
(77, 2, 'Strawberry', 'Wedge', 'Strawberry Wedge', 0),
(78, 1, 'Tomato', 'Original', 'Tomato 3', 0),
(79, 1, 'Tomato', 'Heart', 'Tomato Heart', 0),
(80, 1, 'Tomato', 'Maroon', 'Tomato Maroon', 0),
(81, 1, 'Tomato', 'Yellow', 'Tomato Yellow', 0),
(82, 1, 'Tomato', 'Not Ripened', 'Tomato not Ripened', 0),
(83, 0, 'Walnut', 'Original', 'Walnut', 0),
(84, 0, 'Watermelon', 'Original', 'Watermelon', 0),

(85, 0, 'Cactus fruit', 'Original', 'Cactus fruit', 0),
(86, 0, 'Carambula', 'Original', 'Carambula', 0),
(87, 0, 'Chestnut', 'Original', 'Chestnut', 0),
(88, 0, 'Fig', 'Original', 'Fig', 0),
(89, 0, 'Granadilla', 'Original', 'Granadilla', 0),
(90, 0, 'Guava', 'Original', 'Guava', 0),
(91, 0, 'Hazelnut', 'Original', 'Hazelnut', 0),
(92, 1, 'Kohlrabi', 'Original', 'Kohlrabi', 0),
(93, 0, 'Kumquat', 'Original', 'Kumquats', 0),
(94, 0, 'Lychee', 'Original', 'Lychee', 0),
(95, 0, 'Mangostan', 'Original', 'Mangostan', 0),
(96, 0, 'Maracuja', 'Original', 'Maracuja', 0),
(97, 0, 'Nut', 'Forest', 'Nut Forest', 0),
(98, 0, 'Nut', 'Pecan', 'Nut Pecan', 0),
(99, 0, 'Papaya', 'Original', 'Papaya', 0),
(100, 0, 'Pear', 'Stone', 'Pear Stone', 0),
(101, 2, 'Physalis', 'Original', 'Physalis', 0),
(102, 1, 'Potato', 'Red', 'Potato Red', 0),
(103, 0, 'Rambutan', 'Original', 'Rambutan', 0),
(104, 2, 'Redcurrant', 'Original', 'Redcurrant', 0),
(105, 0, 'Salak', 'Original', 'Salak', 0),
(106, 0, 'Tamarillo', 'Original', 'Tamarillo', 0),
(107, 0, 'Mandarine', 'Tangelos', 'Tangelo', 0),
(108, 1, 'Tomato', 'Cherry Red', 'Tomato Cherry Red', 0),
(109, 0, 'Pepino', 'Original', 'Pepino', 0);
